services:
  - type: web
    name: fullstack-app
    runtime: python
    buildCommand: |
      poetry install && 
      cd frontend &&  # Move to frontend directory
      npm install && 
      npm run build && 
      cd ../backend && 
      poetry run python manage.py migrate && 
      poetry run python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: NODE_VERSION
        value: 18.18.2
